In [99]:
import pandas as pd
import numpy as np

In [100]:
file = pd.read_csv('tweet_amb_ids_match.csv')
file.head()

Unnamed: 0                                              Tweet  \
0           0  Desde el #FCJumilla damos nuestra más sincera ...   
1           1  Me estoy volviendo loca hasta por cada una de ...   
2           2  🏟 | El #FCJumilla ya está en La Condomina   ⚽️...   
3           3  📹 | El vestuario del #FCJumilla en La Condomin...   
4           4  📑 Jornada 6 | El colegiado andaluz Guzmán Mans...   

                                              j_user           created_at  \
0  {'id': 2664945430, 'id_str': '2664945430', 'na...  2018-09-30 15:58:44   
1  {'id': 713359736, 'id_str': '713359736', 'name...  2018-09-24 03:05:47   
2  {'id': 2664945430, 'id_str': '2664945430', 'na...  2018-09-30 15:38:18   
3  {'id': 2664945430, 'id_str': '2664945430', 'na...  2018-09-30 15:19:29   
4  {'id': 2664945430, 'id_str': '2664945430', 'na...  2018-09-30 15:10:30   

   followers_user  FC  RT  trending_topic  \
0            7162  18   4             0.0   
1             531   0   0             0.0   
2            7162   4   2             0.0   
3            7162  21   6             0.0   
4            7162   0   0             0.0   

                                       hashtags_text            id  hour  \
0  0                     [ 'FCJumilla']\r\n1     ...  2.664945e+09  15.0   
1  0                     [ 'FCJumilla']\r\n1     ...  7.133597e+08   3.0   
2  0                     [ 'FCJumilla']\r\n1     ...  2.664945e+09  15.0   
3  0                     [ 'FCJumilla']\r\n1     ...  2.664945e+09  15.0   
4  0                     [ 'FCJumilla']\r\n1     ...  2.664945e+09  15.0   

   class_rt  class_fc  
0       0.0       1.0  
1       0.0       0.0  
2       0.0       1.0  
3       0.0       1.0  
4       0.0       1.0

In [101]:
print('y0')
y0_fc = Y_FC[np.asarray(Y_FC)<=10]
pes0 = (np.asarray(y0_fc).shape[0])/(np.asarray(Y_FC).shape[0])
print(pes0)
hist, bin_edges = np.histogram(y0_fc)
print(hist)
print('\ny1:')
y1_fc = Y_FC[np.asarray(Y_FC)>10]
y1_fc = y1_fc[np.asarray(y1_fc)<=100]
pes1 = (np.asarray(y1_fc).shape[0])/(np.asarray(Y_FC).shape[0])
print(pes1)
hist, bin_edges = np.histogram(y1_fc)
print(hist)
print('\ny2:')
y2_fc = Y_FC[np.asarray(Y_FC)>100]
y2_fc = y2_fc[np.asarray(y2_fc)<=1000]
pes2 = (np.asarray(y2_fc).shape[0])/(np.asarray(Y_FC).shape[0])
print(pes2)
hist, bin_edges = np.histogram(y2_fc)
print(hist)
print('\ny3:')
y3_fc = Y_FC[np.asarray(Y_FC)>1000]
y3_fc = y3_fc[np.asarray(y3_fc)<=5000]
pes3 = (np.asarray(y3_fc).shape[0])/(np.asarray(Y_FC).shape[0])
print(pes3)
hist, bin_edges = np.histogram(y3_fc)
print(hist)
print('\ny4:')
y4_fc = Y_FC[np.asarray(Y_FC)>5000]
pes4 = (np.asarray(y4_fc).shape[0])/(np.asarray(Y_FC).shape[0])
print(pes4)
hist, bin_edges = np.histogram(y4_fc)
print(hist)

y0
0.8628735037007706
[13136  7007  2861  1557  1090   763   544   431   374   566]

y1:
0.08653406841095307
[1320  530  291  211  138  110   72   55   63   51]

y2:
0.02823550912247571
[298 144  95  75  67  60  60  40  45  43]

y3:
0.014407115226462795
[126  79  63  50  44  25  22  19  23  22]

y4:
0.007949803539337821
[143  55  19  20   7   8   2   1   4   2]


In [102]:
# Separem Y_RT entre 5 grups: aquells que tenen menys de 5, aquells que tenen entre 6- 20, 
# aquells que tenen entre 21 - 100, aquells que tenen entre 100 i 500 i aquells que tenen mes de 500
# Fem 4 models, nomes per aquells que tenen a partir de 6

print('y0')
y0_rt = Y_RT[np.asarray(Y_RT)<=5]
pes0 = (np.asarray(y0_rt).shape[0])/(np.asarray(Y_RT).shape[0])
print(pes0)
hist, bin_edges = np.histogram(y0_rt)
print(hist)
print('\ny1:')
y1_rt = Y_RT[np.asarray(Y_RT)>5]
y1_rt = y1_rt[np.asarray(y1_rt)<=20]
pes1 = (np.asarray(y1_rt).shape[0])/(np.asarray(Y_RT).shape[0])
print(pes1)
hist, bin_edges = np.histogram(y1_rt)
print(hist)
print('\ny2:')
y2_rt = Y_RT[np.asarray(Y_RT)>20]
y2_rt = y2_rt[np.asarray(y2_rt)<=100]
pes2 = (np.asarray(y2_rt).shape[0])/(np.asarray(Y_RT).shape[0])
print(pes2)
hist, bin_edges = np.histogram(y2_rt)
print(hist)
print('\ny3:')
y3_rt = Y_RT[np.asarray(Y_RT)>100]
y3_rt = y3_rt[np.asarray(y3_rt)<=500]
pes3 = (np.asarray(y3_rt).shape[0])/(np.asarray(Y_RT).shape[0])
print(pes3)
hist, bin_edges = np.histogram(y3_rt)
print(hist)
print('\ny4:')
y4_rt = Y_RT[np.asarray(Y_RT)>500]
pes4 = (np.asarray(y4_rt).shape[0])/(np.asarray(Y_RT).shape[0])
print(pes4)
hist, bin_edges = np.histogram(y4_rt)
print(hist)

print('\n Suma de pesos:', pes0+pes1+pes2+pes3+pes4)

y0
0.8800219304925223
[21735     0  3741     0  1460     0   912     0   627   417]

y1:
0.05948646096676921
[597 210 349 145 127 185  84 113  54  89]

y2:
0.030002132131217447
[293 173 122  92  78  62  59  46  39  21]

y3:
0.019311017026590722
[145 104  85  59  62  32  46  39  33  29]

y4:
0.011178459382900307
[269  47  20   7   8   6   4   1   3   2]

 Suma de pesos: 1.0000000000000002


In [93]:
file['class_fc'] = np.zeros(file.shape[0])
file['class_rt'] = np.zeros(file.shape[0])

file['class_fc'][y1_fc.index] = 1
file['class_fc'][y2_fc.index] = 2
file['class_fc'][y3_fc.index] = 3
file['class_fc'][y4_fc.index] = 4

file['class_rt'][y1_rt.index] = 1
file['class_rt'][y2_rt.index] = 2
file['class_rt'][y3_rt.index] = 3
file['class_rt'][y4_rt.index] = 4

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set 

In [94]:
file.head()

Unnamed: 0                                              Tweet  \
0           0  Desde el #FCJumilla damos nuestra más sincera ...   
1           1  Me estoy volviendo loca hasta por cada una de ...   
2           2  🏟 | El #FCJumilla ya está en La Condomina   ⚽️...   
3           3  📹 | El vestuario del #FCJumilla en La Condomin...   
4           4  📑 Jornada 6 | El colegiado andaluz Guzmán Mans...   

                                              j_user           created_at  \
0  {'id': 2664945430, 'id_str': '2664945430', 'na...  2018-09-30 15:58:44   
1  {'id': 713359736, 'id_str': '713359736', 'name...  2018-09-24 03:05:47   
2  {'id': 2664945430, 'id_str': '2664945430', 'na...  2018-09-30 15:38:18   
3  {'id': 2664945430, 'id_str': '2664945430', 'na...  2018-09-30 15:19:29   
4  {'id': 2664945430, 'id_str': '2664945430', 'na...  2018-09-30 15:10:30   

   followers_user  FC  RT  trending_topic  \
0            7162  18   4             0.0   
1             531   0   0             0.0   
2            7162   4   2             0.0   
3            7162  21   6             0.0   
4            7162   0   0             0.0   

                                       hashtags_text            id  hour  \
0  0                     [ 'FCJumilla']\r\n1     ...  2.664945e+09  15.0   
1  0                     [ 'FCJumilla']\r\n1     ...  7.133597e+08   3.0   
2  0                     [ 'FCJumilla']\r\n1     ...  2.664945e+09  15.0   
3  0                     [ 'FCJumilla']\r\n1     ...  2.664945e+09  15.0   
4  0                     [ 'FCJumilla']\r\n1     ...  2.664945e+09  15.0   

   class_rt  class_fc  
0       0.0       1.0  
1       0.0       0.0  
2       0.0       0.0  
3       1.0       1.0  
4       0.0       0.0

In [95]:
aux_0 = file[file['class_fc']==0]
aux_1 = file[file['class_fc']==1]
aux_2 = file[file['class_fc']==2]
aux_3 = file[file['class_fc']==3]
aux_4 = file[file['class_fc']==4]
y_0 = aux_0['FC']
y_1 = aux_1['FC']
y_2 = aux_2['FC']
y_3 = aux_3['FC']
y_4 = aux_4['FC']

In [96]:
print(min(y_0),max(y_0))
print(min(y_1),max(y_1))
print(min(y_2),max(y_2))
print(min(y_3),max(y_3))
print(min(y_4),max(y_4))

0 10
11 100
101 1000
1001 4997
5015 77142


In [98]:
aux_0 = file[file['class_rt']==0]
aux_1 = file[file['class_rt']==1]
aux_2 = file[file['class_rt']==2]
aux_3 = file[file['class_rt']==3]
aux_4 = file[file['class_rt']==4]
y_0 = aux_0['RT']
y_1 = aux_1['RT']
y_2 = aux_2['RT']
y_3 = aux_3['RT']
y_4 = aux_4['RT']

print(min(y_0),max(y_0))
print(min(y_1),max(y_1))
print(min(y_2),max(y_2))
print(min(y_3),max(y_3))
print(min(y_4),max(y_4))

0 5
6 20
21 100
101 500
502 16587


## Fins aquí tenim la base de dades d'author i tweet juntes, i s'han afegit dues columnes segons el grup de rt i el grup de fc

Ara preparem les dades per aplicar el model que separa en grups a author

In [ ]:
#model to determine which class

#Neural networks
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler

#for FC

r_state = [0,1,2,3,4,5,42,43,44,45]

acc = np.zeros((len(r_state),1))

for i in range(len(r_state)):
    X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y_FC, train_size=0.7, random_state=r_state[i])
    
    #Your code here
    scaler = StandardScaler()
    scaler = scaler.fit(X_train)
    X_train_scaled = scaler.transform(X_train)
    X_test_scaled = scaler.transform(X_test) 

    mlp = MLPClassifier() #MLP
    mlp.fit(X_train_scaled,y_train)
    yhat_mlp = mlp.predict(X_test_scaled) 
    
    acc[i,0] = metrics.accuracy_score(y_test,yhat_mlp)

mlp = MLPClassifier()

In [ ]:
import numpy as np
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler
from sklearn import model_selection

from sklearn import metrics
from sklearn import tree
from sklearn import neighbors
from sklearn import svm
from sklearn import ensemble
from sklearn.naive_bayes import BernoulliNB
from sklearn.cluster import KMeans

X_train, X_test, y_train, y_test = model_selection.train_test_split(X_aut_new_RT,Y_aut_RT,test_size=0.3,train_size=0.7,random_state=42)
from scipy import stats
import statsmodels.api as sm




X_train, X_test, y_train, y_test = model_selection.train_test_split(X_aut_new_RT,Y_aut_RT,test_size=0.3,train_size=0.7,random_state=42)
GBC = ensemble.GradientBoostingClassifier(random_state=42)
GBC.fit(X_train,y_train)
yhat_GBC = GBC.predict(X_test)
metrics.accuracy_score(y_test,yhat_GBC)




In [2]:
df_aut = './clean_newauthors.csv'
data_aut = pd.read_csv(df_aut, sep=",")


In [3]:
X_aut = data_aut.drop(['Unnamed: 0','sd_RT','sd_FC','friends_count','favourites_count','statuses_count'], axis=1)
X_aut.head()

RT_l10  FC_l10    FC    RT  followers_count  listed_count
0     2.4    15.5   0.0   0.0          19645.0         662.0
1     0.2     0.8   1.0   0.0           4221.0         340.0
2    17.9    37.2  21.0  10.0        1133925.0        9745.0
3     0.4     1.7   0.0   0.0           5386.0         304.0
4     2.3     3.4   0.0   0.0           1072.0         101.0

In [4]:
Y_aut =  data_aut[['FC','RT']]

In [5]:
y = np.array(Y_aut['RT'])

y[y <= 15] = 1
y[y > 15] = 0

X = X_aut.drop(['FC','RT'], axis=1)

print(len(y[y==0]))
print(len(y[y==1]))

174
2204


In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn import model_selection

from sklearn import metrics
from sklearn import tree
from sklearn import neighbors
from sklearn import svm
from sklearn import ensemble
from sklearn.naive_bayes import BernoulliNB
from sklearn.cluster import KMeans

###for RT
r_state = [0,1,2,3,4,5,42,43,44,45]

acc = np.zeros((len(r_state),8))

for i in range(len(r_state)):
    X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, train_size=0.7, random_state=r_state[i])
    
    #Your code here
    scaler = StandardScaler()
    scaler = scaler.fit(X_train)
    X_train_scaled = scaler.transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    
    nn1 = neighbors.KNeighborsClassifier(n_neighbors=1) #1NN
    nn1.fit(X_train_scaled,y_train)
    yhat_nn1 = nn1.predict(X_test_scaled) 

    nn3 = neighbors.KNeighborsClassifier(n_neighbors=3) #3NN
    nn3.fit(X_train_scaled,y_train)
    yhat_nn3 = nn3.predict(X_test_scaled) 
    
    tr = tree.DecisionTreeClassifier() #Decision Tree
    tr.fit(X_train_scaled,y_train)
    yhat_tr = tr.predict(X_test_scaled)
    
    svm10 = svm.SVC(C=10.0,gamma = 1e-5,random_state=42) 
    svm10.fit(X_train_scaled,y_train)
    yhat_svm10 = svm10.predict(X_test_scaled)
    
    svm100 = svm.SVC(C=100.0,gamma = 1e-5,random_state=42)
    svm100.fit(X_train_scaled,y_train)
    yhat_svm100= svm100.predict(X_test_scaled)
    
    svm1000 = svm.SVC(C=1000.0,gamma = 1e-6,random_state=42)
    svm1000.fit(X_train_scaled,y_train)
    yhat_svm1000 = svm1000.predict(X_test_scaled)
    
    GBC = ensemble.GradientBoostingClassifier(random_state=42)
    GBC.fit(X_train_scaled,y_train)
    yhat_GBC = GBC.predict(X_test_scaled)
    
    clf = KMeans(n_clusters=2)
    clf.fit(X_train_scaled,y_train)
    yhat_clf = clf.predict(X_test_scaled)
    
    acc[i,0] = metrics.accuracy_score(y_test,yhat_tr)
    acc[i,1] = metrics.accuracy_score(y_test,yhat_nn1)
    acc[i,2] = metrics.accuracy_score(y_test,yhat_nn3)
    acc[i,3] = metrics.accuracy_score(y_test,yhat_svm10)
    acc[i,4] = metrics.accuracy_score(y_test,yhat_svm100)
    acc[i,5] = metrics.accuracy_score(y_test,yhat_svm1000)
    acc[i,6] = metrics.accuracy_score(y_test,yhat_GBC)
    acc[i,7] = metrics.accuracy_score(y_test,yhat_clf)
print(acc)

/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


[[0.92857143 0.93417367 0.94537815 0.92997199 0.93977591 0.93977591
  0.94257703 0.06442577]
 [0.95378151 0.94257703 0.95518207 0.93417367 0.94677871 0.94677871
  0.96358543 0.06022409]
 [0.93277311 0.94257703 0.95238095 0.92857143 0.93837535 0.93837535
  0.94817927 0.06722689]
 [0.93557423 0.92577031 0.94957983 0.92016807 0.92997199 0.92997199
  0.94957983 0.92577031]
 [0.93697479 0.92857143 0.93417367 0.92296919 0.94117647 0.94117647
  0.94397759 0.07282913]
 [0.94537815 0.94117647 0.95798319 0.93557423 0.94537815 0.94537815
  0.95798319 0.05882353]
 [0.95238095 0.94397759 0.96078431 0.94257703 0.95378151 0.95378151
  0.96218487 0.05322129]
 [0.93137255 0.93697479 0.96218487 0.92857143 0.94397759 0.94397759
  0.95518207 0.06862745]
 [0.93417367 0.93977591 0.96498599 0.94257703 0.95378151 0.95378151
  0.96078431 0.05182073]
 [0.94257703 0.94117647 0.95658263 0.93417367 0.94677871 0.94677871
  0.95518207 0.06022409]]


In [ ]:
import matplotlib.pyplot as plt

# FREQUENCY PLOT
%matplotlib inline

plt.figure(figsize=(15,8))

# FC Histogram
plt.subplot(2, 2, 1)
plt.hist(x=Y_aut['FC'],density=1, bins=int(np.max(Y_aut['FC']))) 
plt.xlabel('Number of FC classes')
plt.ylabel('Frequency')
plt.xlim(0, 35)

# FC Histogram
plt.subplot(2, 2, 2)
plt.hist(x=Y_aut['RT'],density=1, bins=int(np.max(Y_aut['RT']))) 
plt.xlabel('Number of RT classes')
plt.ylabel('Frequency')
plt.xlim(0, 12.5)

y_FC35 = sorted(np.where(Y_aut['FC']>35)[0])
y_RT35 = sorted(np.where(Y_aut['RT']>35)[0])

plt.subplot(2, 2, 3)
plt.hist(x=y_FC35, bins=int(np.max(Y_aut['FC'])/10)) 
plt.subplot(2, 2, 4)
plt.hist(x=y_RT35, bins=int(np.max(Y_aut['RT'])/10)) 
plt.show()

KeyboardInterrupt: 

In [71]:
X_aut_pois_FC_menys15 = X_aut[X_aut['FC']<3]
X_aut_pois_RT_menys15 = X_aut[X_aut['RT']<3]

X_aut_pois_FC_mes15 = X_aut[X_aut['FC']>5]
X_aut_pois_RT_mes15 = X_aut[X_aut['RT']>5]


Y_aut_RT =  X_aut_pois_RT_menys15[['RT']]
Y_aut_FC =  X_aut_pois_FC_menys15[['FC']]



X_aut_new_RT = X_aut_pois_RT_menys15.drop(['FC','RT'], axis=1)
X_aut_new_FC = X_aut_pois_FC_menys15.drop(['RT'], axis=1)

print(X_aut_new_RT.shape)

print(Y_aut_RT.shape)


(1922, 4)
(1922, 1)


In [72]:
import numpy as np
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler
from sklearn import model_selection

from sklearn import metrics
from sklearn import tree
from sklearn import neighbors
from sklearn import svm
from sklearn import ensemble
from sklearn.naive_bayes import BernoulliNB
from sklearn.cluster import KMeans

X_train, X_test, y_train, y_test = model_selection.train_test_split(X_aut_new_RT,Y_aut_RT,test_size=0.3,train_size=0.7,random_state=42)
from scipy import stats
import statsmodels.api as sm




X_train, X_test, y_train, y_test = model_selection.train_test_split(X_aut_new_RT,Y_aut_RT,test_size=0.3,train_size=0.7,random_state=42)
GBC = ensemble.GradientBoostingClassifier(random_state=42)
GBC.fit(X_train,y_train)
yhat_GBC = GBC.predict(X_test)
metrics.accuracy_score(y_test,yhat_GBC)







/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.804159445407279

In [2]:
import pandas as pd
import numpy as np

In [3]:
filename = './tweet.csv'
data = pd.read_csv(filename, sep=",")

In [4]:
# Hi ha més d'un tweet per 'id' en alguns casos (màxim 4)
ctrl_01 = data.groupby('id').id.count()
ctrl_01.sort_values().tail(7)

id
1060974074799775746    2
1060975078630809600    2
1060976088380256256    2
1060974115832676353    2
1060975059559481350    2
1061341603984490496    2
1060975842304638977    2
Name: id, dtype: int64

Check number of zeros in  'FC' and 'RT' of our sample:

In [5]:
zero_ratio_FC = data.loc[data.index[data['FC'] > 0]].shape[0]/data.shape[0]
zero_ratio_RT = data.loc[data.index[data['RT'] > 0]].shape[0]/data.shape[0]

print('Una accuarcy semblant a aquest ratios seria dolenta, ha de ser molt més')
print(1-zero_ratio_FC, 1-zero_ratio_RT)

Una accuarcy semblant a aquest ratios seria dolenta, ha de ser molt més
0.40010965246261154 0.6620267430172703


In [6]:
X = data.drop(['Unnamed: 0','FC','RT','trending_topic','followers_user','trending_topic'], axis=1)
X.head()

id                                              Tweet  \
0  1046429145914384386  Desde el #FCJumilla damos nuestra más sincera ...   
1  1044060298443919367  Me estoy volviendo loca hasta por cada una de ...   
2  1046424001214648320  🏟 | El #FCJumilla ya está en La Condomina   ⚽️...   
3  1046419267279818752  📹 | El vestuario del #FCJumilla en La Condomin...   
4  1046417005451128832  📑 Jornada 6 | El colegiado andaluz Guzmán Mans...   

                                              j_user           created_at  \
0  {'id': 2664945430, 'id_str': '2664945430', 'na...  2018-09-30 15:58:44   
1  {'id': 713359736, 'id_str': '713359736', 'name...  2018-09-24 03:05:47   
2  {'id': 2664945430, 'id_str': '2664945430', 'na...  2018-09-30 15:38:18   
3  {'id': 2664945430, 'id_str': '2664945430', 'na...  2018-09-30 15:19:29   
4  {'id': 2664945430, 'id_str': '2664945430', 'na...  2018-09-30 15:10:30   

                                            entities  
0  {'hashtags': [{'text': 'FCJumilla', 'indices':...  
1  {'hashtags': [], 'symbols': [], 'user_mentions...  
2  {'hashtags': [{'text': 'FCJumilla', 'indices':...  
3  {'hashtags': [{'text': 'FCJumilla', 'indices':...  
4  {'hashtags': [{'text': 'UCAMMurciaJumilla', 'i...

In [7]:
Y = data[['FC','RT']]
Y.head()

FC  RT
0  18   4
1   0   0
2   4   2
3  21   6
4   0   0

In [ ]:
import matplotlib.pyplot as plt

# FREQUENCY PLOT
%matplotlib inline

plt.figure(figsize=(15,8))

# FC Histogram
plt.subplot(2, 2, 1)
plt.hist(x=Y['FC'],density=1, bins=int(np.max(Y['FC']))) 
plt.xlabel('Number of FC classes')
plt.ylabel('Frequency')
plt.xlim(0, 35)

# FC Histogram
plt.subplot(2, 2, 2)
plt.hist(x=Y['RT'],density=1, bins=int(np.max(Y['RT']))) 
plt.xlabel('Number of RT classes')
plt.ylabel('Frequency')
plt.xlim(0, 12.5)

y_FC35 = sorted(np.where(Y['FC']>35)[0])
y_RT35 = sorted(np.where(Y['RT']>35)[0])

plt.subplot(2, 2, 3)
plt.hist(x=y_FC35, bins=int(np.max(Y['FC'])/10)) 
plt.subplot(2, 2, 4)
plt.hist(x=y_RT35, bins=int(np.max(Y['RT'])/10)) 
plt.show()

Resum: La majoria de 'FC' es concentra entre 0 i 10 i entre 0 i 5 a 'RT'. Això podria infuir a l'hora de fer els models xq la BBDD de tweets amb 'FC' i 'RT' es molt petita i la predicció serà dolenta. No els podem considerar Outliers perquè realment no ho són (gent famosa per exemple). Hauriem de fer diferents models per diferents grups de persones, és a dir, en funció de la mitja dels RT i FC anteriors aplicar-li un model o altres. Podem separar la mostra no per FC i RT sinó per RT_l10, sd_RT, FC_l10 i/o sd_FC que ve de la bbdd 'author'. L'aplicació podria aplicarte un model o un altre amb els paràmetres estimats.

In [8]:
print(len(np.where(Y['FC']>35)[0]), len(np.where(Y['RT']>35)[0]), len(Y)) #2410 1539 32831

2410 1539 32831


La següent funció assigna una classe a cada interval. En total 137 classes 137 intervals. A mesura que els FC i els RT augmenten també augmenta l'amplada del interval:

In [9]:
class segmenta():
    
    def __init__(self):
        self.intervals = {}
    
    def transform(self,y):
        k, z = 0, 0
        for a, b in [[15,5],
                     [100,5],
                     [200,10],
                     [500,20],
                     [1000,50],
                     [5000,100],
                     [10000,500],
                     [50000,2000]]: 
            for i in np.arange(z,a,b):
                self.intervals[k] = [i,i+b-1]
                k+=1
            z = a
        self.intervals[k] = [50000,99999999]

        y = np.reshape(y.values, (-1,1))
        for j in self.intervals:
            c = self.intervals[j]
            idx = np.where(np.logical_and(y>=c[0],y<=c[1]))[0]
            y[idx] = j

        return y


In [10]:
Y = data[['FC','RT']]

segFC = segmenta()
Y['FC'] = segFC.transform(Y['FC'])

segRT = segmenta()
Y['RT'] = segRT.transform(Y['RT'])

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys


In [11]:
Y.tail()

FC  RT
32826   2   0
32827  20  12
32828   8   4
32829   0   0
32830   1   0

### Location i Tweets###

In [12]:
import ast
import re #regular expressions
import unidecode as udc
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from unicodedata import normalize

In [13]:
X['location'] = [ast.literal_eval(data['j_user'][i])['location'] for i in range(X.shape[0])]

In [14]:
X.head()

id                                              Tweet  \
0  1046429145914384386  Desde el #FCJumilla damos nuestra más sincera ...   
1  1044060298443919367  Me estoy volviendo loca hasta por cada una de ...   
2  1046424001214648320  🏟 | El #FCJumilla ya está en La Condomina   ⚽️...   
3  1046419267279818752  📹 | El vestuario del #FCJumilla en La Condomin...   
4  1046417005451128832  📑 Jornada 6 | El colegiado andaluz Guzmán Mans...   

                                              j_user           created_at  \
0  {'id': 2664945430, 'id_str': '2664945430', 'na...  2018-09-30 15:58:44   
1  {'id': 713359736, 'id_str': '713359736', 'name...  2018-09-24 03:05:47   
2  {'id': 2664945430, 'id_str': '2664945430', 'na...  2018-09-30 15:38:18   
3  {'id': 2664945430, 'id_str': '2664945430', 'na...  2018-09-30 15:19:29   
4  {'id': 2664945430, 'id_str': '2664945430', 'na...  2018-09-30 15:10:30   

                                            entities         location  
0  {'hashtags': [{'text': 'FCJumilla', 'indices':...  Jumilla, España  
1  {'hashtags': [], 'symbols': [], 'user_mentions...        Atlantida  
2  {'hashtags': [{'text': 'FCJumilla', 'indices':...  Jumilla, España  
3  {'hashtags': [{'text': 'FCJumilla', 'indices':...  Jumilla, España  
4  {'hashtags': [{'text': 'UCAMMurciaJumilla', 'i...  Jumilla, España

1a Opció: Token, analyze, ...

Script Núria en el que es treuen les paraules que no aporten informació com conectors, articles, ... per utilitzaro com a stop words en el 'CountVectorizer':

In [15]:
filename = './eliminar_paraules.xlsx'
elim = pd.read_excel(filename, header=None)

y=elim[0]
for i in range(len(elim)):
    y[i] = re.sub(
            r"([^n\u0300-\u036f]|n(?!\u0303(?![\u0300-\u036f])))[\u0300-\u036f]+", r"\1", 
            normalize( "NFD", y[i]), 0, re.I)
y = y.tolist()

In [16]:
vectorizer1 = CountVectorizer(min_df=0.0001, stop_words=y, strip_accents='unicode') # Tweets 
vectorizer2 = CountVectorizer(min_df=0.001, stop_words=y, strip_accents='unicode') # location

### CLASSIFIERS ###

In [17]:
# Classifiers importation
from sklearn.metrics import log_loss
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC, NuSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn import neural_network
from sklearn.naive_bayes import BernoulliNB

# Others
import seaborn as sns
from sklearn import linear_model, metrics, model_selection
from sklearn.preprocessing import StandardScaler

In [18]:
classifiers = [ neural_network.MLPClassifier(),
                linear_model.LogisticRegression(),
                KNeighborsClassifier(3),
                SVC(kernel="rbf", C=1, probability=True),
#               NuSVC(probability=True),
                DecisionTreeClassifier(),
                RandomForestClassifier(),
                AdaBoostClassifier(),
                GradientBoostingClassifier(),
                GaussianNB(),
                BernoulliNB()
#               LinearDiscriminantAnalysis(),
#               QuadraticDiscriminantAnalysis()
              ]

In [19]:
# FC
Y_FC = Y['FC']

X_train, X_test, y_train, y_test = model_selection.train_test_split(X,Y_FC,test_size=0.3,train_size=0.7,random_state=42)

#Process and convert data 
a1 = vectorizer1.fit_transform(X_train['Tweet'])
a1 = a1.todense()                                                                                                                                                                                                                                         
#a2 = vectorizer2.fit_transform(X_train['location'])
#a2 = a2.todense() 
#X_train = np.concatenate((a1, a2), axis=1)
X_train = a1
y_train = y_train.values

b1 = vectorizer1.transform(X_test['Tweet'])
b1 = b1.todense()
#b2 = vectorizer2.transform(X_test['location'])
#b2 = b2.todense()
#X_test = np.concatenate((b1, b2), axis=1)
X_test = b1
y_test = y_test.values

In [20]:
print(X_train.shape)
print(X_test.shape)

# Percentatge número de files amb tot zeros despres de natejar la bbdd (X_train i X_test)
print(X_train[np.where(X_train.sum(axis=1)>0)].shape[1]/X_train.shape[0])
print(X_test[np.where(X_test.sum(axis=1)>0)].shape[1]/X_test.shape[0])

(22981, 9871)
(9850, 9871)
0.9676689439101867
0.9602030456852791


In [ ]:
# Logging for Visual Comparison
log_cols=["Classifier", "Accuracy"]
log = pd.DataFrame(columns=log_cols)

for clf in classifiers:

    clf.fit(X_train,y_train)
    name = clf.__class__.__name__

    yhat = clf.predict(X_test).reshape(-1,1)
    acc = metrics.accuracy_score(y_test, yhat)  
    print(name, acc)
    yhat_prob = clf.predict_proba(X_test)

    log_entry = pd.DataFrame([[name, acc*100]], columns=log_cols)
    log = log.append(log_entry)

# ACCURACY GRAPHIC 
sns.set_color_codes("muted")
sns.barplot(x='Accuracy', y='Classifier', data=log, color="b")

plt.xlabel('Accuracy %')
plt.title('Classifier Accuracy')
plt.show()

MLPClassifier 0.7068020304568527
LogisticRegression 0.7751269035532995


In [31]:
log

Classifier   Accuracy
0       MLPClassifier  73.801816
0  LogisticRegression  59.091986

In [ ]:
# RT
Y_RT = Y['RT']

X_train, X_test, y_train, y_test = model_selection.train_test_split(X,Y_RT,test_size=0.3,train_size=0.7,random_state=42)

#Process and convert data 
a1 = vectorizer1.fit_transform(X_train['Tweet'])
a1 = a1.todense()                                                                                                                                                                                                                                         
#a2 = vectorizer2.fit_transform(X_train['location'])
#a2 = a2.todense() 
#X_train = np.concatenate((a1, a2), axis=1)
X_train = a1
y_train = y_train.values

b1 = vectorizer1.transform(X_test['Tweet'])
b1 = b1.todense()
#b2 = vectorizer2.transform(X_test['location'])
#b2 = b2.todense()
#X_test = np.concatenate((b1, b2), axis=1)
X_test = b1
y_test = y_test.values

In [ ]:
print(X_train.shape)
print(X_test.shape)

# Percentatge número de files amb tot zeros despres de natejar la bbdd (X_train i X_test)
print(X_train[np.where(X_train.sum(axis=1)>0)].shape[1]/X_train.shape[0])
print(X_test[np.where(X_test.sum(axis=1)>0)].shape[1]/X_test.shape[0])

In [ ]:
# Logging for Visual Comparison
log_cols=["Classifier", "Accuracy"]
log = pd.DataFrame(columns=log_cols)

for clf in classifiers:

    clf.fit(X_train,y_train)
    name = clf.__class__.__name__

    yhat = clf.predict(X_test).reshape(-1,1)
    acc = metrics.accuracy_score(y_test, yhat)   
    yhat_prob = clf.predict_proba(X_test)

    log_entry = pd.DataFrame([[name, acc*100]], columns=log_cols)
    log = log.append(log_entry)

# ACCURACY GRAPHIC 
sns.set_color_codes("muted")
sns.barplot(x='Accuracy', y='Classifier', data=log, color="b")

plt.xlabel('Accuracy %')
plt.title('Classifier Accuracy')
plt.show()

In [ ]:
y = np.array(Y_RT)

y[y <= 215] = 1
y[y > 250] = 0

print(len(y[y==0]))
print(len(y[y==1]))

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn import model_selection

from sklearn import metrics
from sklearn import tree
from sklearn import neighbors
from sklearn import svm
from sklearn import ensemble
from sklearn.naive_bayes import BernoulliNB
from sklearn.cluster import KMeans

###for RT
r_state = [0,1,2,3,4,5,42,43,44,45]

acc = np.zeros((len(r_state),8))

for i in range(len(r_state)):
    X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, train_size=0.7, random_state=r_state[i])
    
    #Your code here
    scaler = StandardScaler()
    scaler = scaler.fit(X_train)
    X_train_scaled = scaler.transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    
    nn1 = neighbors.KNeighborsClassifier(n_neighbors=1) #1NN
    nn1.fit(X_train_scaled,y_train)
    yhat_nn1 = nn1.predict(X_test_scaled) 

    nn3 = neighbors.KNeighborsClassifier(n_neighbors=3) #3NN
    nn3.fit(X_train_scaled,y_train)
    yhat_nn3 = nn3.predict(X_test_scaled) 
    
    tr = tree.DecisionTreeClassifier() #Decision Tree
    tr.fit(X_train_scaled,y_train)
    yhat_tr = tr.predict(X_test_scaled)
    
    svm10 = svm.SVC(C=10.0,gamma = 1e-5,random_state=42) 
    svm10.fit(X_train_scaled,y_train)
    yhat_svm10 = svm10.predict(X_test_scaled)
    
    svm100 = svm.SVC(C=100.0,gamma = 1e-5,random_state=42)
    svm100.fit(X_train_scaled,y_train)
    yhat_svm100= svm100.predict(X_test_scaled)
    
    svm1000 = svm.SVC(C=1000.0,gamma = 1e-6,random_state=42)
    svm1000.fit(X_train_scaled,y_train)
    yhat_svm1000 = svm1000.predict(X_test_scaled)
    
    GBC = ensemble.GradientBoostingClassifier(random_state=42)
    GBC.fit(X_train_scaled,y_train)
    yhat_GBC = GBC.predict(X_test_scaled)
    
    clf = KMeans(n_clusters=2)
    clf.fit(X_train_scaled,y_train)
    yhat_clf = clf.predict(X_test_scaled)
    
    acc[i,0] = metrics.accuracy_score(y_test,yhat_tr)
    acc[i,1] = metrics.accuracy_score(y_test,yhat_nn1)
    acc[i,2] = metrics.accuracy_score(y_test,yhat_nn3)
    acc[i,3] = metrics.accuracy_score(y_test,yhat_svm10)
    acc[i,4] = metrics.accuracy_score(y_test,yhat_svm100)
    acc[i,5] = metrics.accuracy_score(y_test,yhat_svm1000)
    acc[i,6] = metrics.accuracy_score(y_test,yhat_GBC)
    acc[i,7] = metrics.accuracy_score(y_test,yhat_clf)